#!/bin/ksh
echo "usage: doAtom Symbol charge alpha spin"
mkmesh $1 mhl,100 gauss,1 
echo  $1 $2 0,0,0 - - >$1.atm
mkcl $1
echo 0 25 0.05 75000.0  >$1.bsd
echo 1 15 0.13   925.0 >>$1.bsd
echo 2 12 0.01    30.0 >>$1.bsd
mkbas -v $1 sg  
echo 0 25  0.01 75000.0  >$1.exp
mkbas -vc  $1 sg  
mkbas -vxn $1 sg  
mkcd $1 -g
mkham $1 $3  -p 
scfiter $1 -e1e-4 -x0.6 -n20 -p$4

